# coding: utf-8

"""
    Furhat Remote API

    This is the Furhat Remote API, used to control the Furhat robot from e.g. Python. Note that the Furhat Remote API Skill needs to be running on the robot for it to work. Find out more at https://docs.furhat.io/remote-api  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: support@furhatrobotics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Frame(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time': 'list[float]',
        'params': 'BasicParam'
    }

    attribute_map = {
        'time': 'time',
        'params': 'params'
    }

    def __init__(self, time=None, params=None, _configuration=None):  # noqa: E501
        """Frame - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._time = None
        self._params = None
        self.discriminator = None

        if time is not None:
            self.time = time
        if params is not None:
            self.params = params

    @property
    def time(self):
        """Gets the time of this Frame.  # noqa: E501


        :return: The time of this Frame.  # noqa: E501
        :rtype: list[float]
        """
        return self._time

    @time.setter
    def time(self, time):
        """Sets the time of this Frame.


        :param time: The time of this Frame.  # noqa: E501
        :type: list[float]
        """

        self._time = time

    @property
    def params(self):
        """Gets the params of this Frame.  # noqa: E501


        :return: The params of this Frame.  # noqa: E501
        :rtype: BasicParam
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this Frame.


        :param params: The params of this Frame.  # noqa: E501
        :type: BasicParam
        """

        self._params = params

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Frame, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Frame):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Frame):
            return True

        return self.to_dict() != other.to_dict()
