# coding: utf-8

"""
    Furhat Remote API

    This is the Furhat Remote API, used to control the Furhat robot from e.g. Python. Note that the Furhat Remote API Skill needs to be running on the robot for it to work. Find out more at https://docs.furhat.io/remote-api  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: support@furhatrobotics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class GestureDefinition(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'frames': 'list[Frame]',
        '_class': 'str'
    }

    attribute_map = {
        'name': 'name',
        'frames': 'frames',
        '_class': 'class'
    }

    def __init__(self, name=None, frames=None, _class=None, _configuration=None):  # noqa: E501
        """GestureDefinition - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._frames = None
        self.__class = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if frames is not None:
            self.frames = frames
        if _class is not None:
            self._class = _class

    @property
    def name(self):
        """Gets the name of this GestureDefinition.  # noqa: E501


        :return: The name of this GestureDefinition.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GestureDefinition.


        :param name: The name of this GestureDefinition.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def frames(self):
        """Gets the frames of this GestureDefinition.  # noqa: E501


        :return: The frames of this GestureDefinition.  # noqa: E501
        :rtype: list[Frame]
        """
        return self._frames

    @frames.setter
    def frames(self, frames):
        """Sets the frames of this GestureDefinition.


        :param frames: The frames of this GestureDefinition.  # noqa: E501
        :type: list[Frame]
        """

        self._frames = frames

    @property
    def _class(self):
        """Gets the _class of this GestureDefinition.  # noqa: E501


        :return: The _class of this GestureDefinition.  # noqa: E501
        :rtype: str
        """
        return self.__class

    @_class.setter
    def _class(self, _class):
        """Sets the _class of this GestureDefinition.


        :param _class: The _class of this GestureDefinition.  # noqa: E501
        :type: str
        """

        self.__class = _class

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GestureDefinition, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GestureDefinition):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GestureDefinition):
            return True

        return self.to_dict() != other.to_dict()
