# coding: utf-8

# flake8: noqa

"""
    Furhat Remote API

    This is the Furhat Remote API, used to control the Furhat robot from e.g. Python. Note that the Furhat Remote API Skill needs to be running on the robot for it to work. Find out more at https://docs.furhat.io/remote-api  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: support@furhatrobotics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.furhat_api import FurhatApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.basic_param import BasicParam
from swagger_client.models.frame import Frame
from swagger_client.models.gesture import Gesture
from swagger_client.models.gesture_definition import GestureDefinition
from swagger_client.models.location import Location
from swagger_client.models.rotation import Rotation
from swagger_client.models.status import Status
from swagger_client.models.user import User
from swagger_client.models.voice import Voice
