# coding: utf-8

"""
    Furhat Remote API

    This is the Furhat Remote API, used to control the Furhat robot from e.g. Python. Note that the Furhat Remote API Skill needs to be running on the robot for it to work. Find out more at https://docs.furhat.io/remote-api  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: support@furhatrobotics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.furhat_api import FurhatApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFurhatApi(unittest.TestCase):
    """FurhatApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.furhat_api.FurhatApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_furhat_attend_post(self):
        """Test case for furhat_attend_post

        Attend a user/location  # noqa: E501
        """
        pass

    def test_furhat_face_post(self):
        """Test case for furhat_face_post

        Change the texture and/or model  # noqa: E501
        """
        pass

    def test_furhat_gesture_post(self):
        """Test case for furhat_gesture_post

        Perform a gesture  # noqa: E501
        """
        pass

    def test_furhat_gestures_get(self):
        """Test case for furhat_gestures_get

        Get all gestures  # noqa: E501
        """
        pass

    def test_furhat_get(self):
        """Test case for furhat_get

        Test connection  # noqa: E501
        """
        pass

    def test_furhat_led_post(self):
        """Test case for furhat_led_post

        Change the colour of the LED strip  # noqa: E501
        """
        pass

    def test_furhat_listen_get(self):
        """Test case for furhat_listen_get

        Make the robot listen, and get speech results  # noqa: E501
        """
        pass

    def test_furhat_listen_stop_post(self):
        """Test case for furhat_listen_stop_post

        Make the robot stop listening  # noqa: E501
        """
        pass

    def test_furhat_say_post(self):
        """Test case for furhat_say_post

        Make the robot speak  # noqa: E501
        """
        pass

    def test_furhat_say_stop_post(self):
        """Test case for furhat_say_stop_post

        Make the robot stop talking  # noqa: E501
        """
        pass

    def test_furhat_users_get(self):
        """Test case for furhat_users_get

        Get current users  # noqa: E501
        """
        pass

    def test_furhat_visibility_post(self):
        """Test case for furhat_visibility_post

        Fade in/out the face  # noqa: E501
        """
        pass

    def test_furhat_voice_post(self):
        """Test case for furhat_voice_post

        Set the voice of the robot  # noqa: E501
        """
        pass

    def test_furhat_voices_get(self):
        """Test case for furhat_voices_get

        Get all the voices on the robot  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
