# coding: utf-8

"""
    Furhat Remote API

    This is the Furhat Remote API, used to control the Furhat robot from e.g. Python. Note that the Furhat Remote API Skill needs to be running on the robot for it to work. Find out more at https://docs.furhat.io/remote-api  # noqa: E501

    OpenAPI spec version: 1.0.2
    Contact: support@furhatrobotics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.basic_param import BasicParam  # noqa: E501
from swagger_client.rest import ApiException


class TestBasicParam(unittest.TestCase):
    """BasicParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBasicParam(self):
        """Test BasicParam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.basic_param.BasicParam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
